### ISSUE TITLE
Lecture 22-Apr-2024, Session 10 Neural network intro, ANN with spreadsheet

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#10]
+ Study [slide-10a](https://osf.io/3ksmu), [slide-10b](https://osf.io/42tq9).
+ Accept the challenges there in a Notebook.
+ Publish it as a Gist.
+ Share link to the Gist here.

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/6bb3779ffc24ff85c0c115ea5755e67d

**Comment by charlesmana** [comment]
Charnadi Lesmana
21181068
https://gist.github.com/charlesmana/829d115fa55d9bdc6bf640b499df9dea

**Comment by NerdyVandheka** [comment]
Nerdy Vandheka
21181213
https://gist.github.com/NerdyVandheka/023fa3862b8458fecdb6cb06ed5af3dc

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA PUTRA
21181284
https://gist.github.com/tegarhermans/234ec935cae0d042ebb5504ae738d06b

**Comment by ayodyaadhi01** [comment]
AYODYA ADHI
21181017
https://gist.github.com/ayodyaadhi01/e2e5573de15fdd5a78b68ecb7b5373ab

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
https://gist.github.com/NeganSmith92/fbe5f29762381a2dda525cf45203faf0

**Comment by afrozhie** [comment]
FIRMAN ANDRIAN
21181094

https://gist.github.com/afrozhie/b706d50ddc8b6f6196a7db0522ef728b

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

https://gist.github.com/Ptolemu5/153c269001046ada680c82eb09109167

**Comment by MazamGanendra** [comment]
Mazam Ganendra
21181192
https://gist.github.com/MazamGanendra/b4c219333c3656873d2a25c13c1cd595

**Comment by Antara000** [comment]
Makmur Perkasa
21181161
https://gist.github.com/Antara000/b06f9c1eaea0cf0d3534383df64ae563

**Comment by CyberianRonin** [comment]
Resna Febrianto
21181229
https://gist.github.com/CyberianRonin/a619a2f845bce89ffa6c61b046ad612f

**Comment by robinhuud15** [comment]
ROBIN HUDSON
21181234
https://gist.github.com/robinhuud15/59d26f4112f10451d70e60f84649a9d2

**Comment by CriticalOlymp** [comment]
Chandra Martadinata
21181064
https://gist.github.com/CriticalOlymp/03a0e53dd959c4d64c66c780d1287ea0

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195

https://gist.github.com/narapatimulia/10ed65aa1f860e07866f1d5d86cb2258

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241
https://gist.github.com/birongzah/c06c86cdbcf4b895968a050b2ff9c0db

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/0e63605f93f0b49d109b2b27026d2daa

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085

https://gist.github.com/IZAN0R/578dbcf94a0e7fcde5e5ef4828aa543d

**Comment by bahrudinz** [comment]
Mudzafar Azzam
21181177

https://gist.github.com/bahrudinz/6d150d4208c00ed3856db77769f18876

**Comment by yunoooo111** [comment]
Yurnero Nolla
21181296

https://gist.github.com/yunoooo111/d5a08b052c269601ed0b9ff44752b02a

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/1b46d76f4e5f8c7bf9f9d80ec0e37dd6

**Comment by irhwam** [comment]
NIT: 21181125
Irham Prajawiguna
https://gist.github.com/irhwam/4cf515dc0ac90e44b3266c844d9f3b96

**Comment by AKS4R4** [comment]
RASHA MUHAMMAD
21181236
https://gist.github.com/AKS4R4/c3adbead392b3e134dc204ec3d9fede0
Support By: Zafran Marvis

**Comment by yunisangadji** [comment]
YULIA VALONIA
21181298

https://gist.github.com/yunisangadji/5786a850b615723503ea0682152c922a

**Comment by heksamolako25** [comment]
Heksandro M
21181117

https://gist.github.com/heksamolako25/8a542e8ecb83704cb21b2ecdf642ccb5
