### ISSUE TITLE
Lecture 22-Apr-2024, Session 11 Practicing Python for ML with Iris and synthetic datasets

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#11]
+ Study [slide-11a](https://osf.io/k8b7q) and [slide-11b](https://osf.io/wqv3z).
+ Accept the challenges there in a Notebook.
+ Publish it as a Gist.
+ Share link to the Gist here.

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
https://gist.github.com/NeganSmith92/98674e569f0d5653e61ca0334a92c710

**Comment by NerdyVandheka** [comment]
NERDY VANDHEKA 
21181213
ABSEN 16
https://gist.github.com/NerdyVandheka/3d794f47b2d0b0e2686946e936547761

**Comment by Ptolemu5** [comment]
Murrobi Fatahlillah
21181203

https://gist.github.com/Ptolemu5/5fb25074e503a15931608611d6949818

**Comment by ayodyaadhi01** [comment]
Ayodya Adhi
21181017
https://gist.github.com/ayodyaadhi01/338d12d800c1c8f7d9a00259b54d050c

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA PUTRA
21181284
https://gist.github.com/tegarhermans/b7b276af6b8b3a609a4081360ae9dd5b

**Comment by MazamGanendra** [comment]
Mazam Ganendra
21181192
https://gist.github.com/MazamGanendra/39f1d6198b281a39e9e8e5bd11d8d464

**Comment by afrozhie** [comment]
Firman Andrian
21181094
https://gist.github.com/afrozhie/54b63268ed5b2d15101cdd064ebed4e0

**Comment by Antara000** [comment]
Makmur Perkasa
21181161
https://gist.github.com/Antara000/7242644575149bcd2ab054b9154f9d55

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/a9826b07d3b4559486a6e3e7c932ed19

**Comment by CyberianRonin** [comment]
Resna Febrianto
21181229
https://gist.github.com/CyberianRonin/db48fc23d5137f074f117c6a1ff03468

**Comment by robinhuud15** [comment]
ROBIN HUDSON
21181234
https://gist.github.com/robinhuud15/a831fa9533a2cf45d9734639230f00de

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/7e07882660212214fab1cb3acff2d120

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195

https://gist.github.com/narapatimulia/191c018c2699e1e5af28bed3c561005a

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085

https://gist.github.com/IZAN0R/a24f432ac16a08cb442fc20e847145ba

**Comment by bahrudinz** [comment]
Mudzafar Azzam
21181177

https://gist.github.com/bahrudinz/dda8c032d92c9fca651c34cb88a4f7b3

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241
https://gist.github.com/birongzah/02c29f0e1ba7a0445308db5f44e017d3

**Comment by CriticalOlymp** [comment]
Chandra Martadinata
21181064
https://gist.github.com/CriticalOlymp/59656988380152719c36c1e9b979811d

**Comment by yunoooo111** [comment]
Yurnero Nolla
21181296
https://gist.github.com/yunoooo111/1b67ef213084b0db6079092c13f05063

**Comment by charlesmana** [comment]
CHARNADI LESMANA
21181068
https://gist.github.com/charlesmana/13d44eaec794fade0aec3e3c9250cc75

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/b7550bcb72656e3451f5109e9d219290

**Comment by irhwam** [comment]
21181125
Irham Prajawiguna
https://gist.github.com/irhwam/274201370d5a49320a6ed2a05e57bb18

**Comment by AKS4R4** [comment]
RASHA MUHAMMAD
21181236
https://gist.github.com/AKS4R4/e160b1e14ca4d3ec17e214c7e65ad1af
Support By: Zafran Marvis

**Comment by yunisangadji** [comment]
YULIA VALONIA
21181298

https://gist.github.com/yunisangadji/2588793954cb517bf9a2dcda1093b401

**Comment by heksamolako25** [comment]
Heksandro Molako
21181117

https://gist.github.com/heksamolako25/d06b0410bd867a02bb73fc2c4cf69fce
