### ISSUE TITLE
Lecture 17-May-2024, Session 13 TensorFlow Playground

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#13]
Read [the slide](https://osf.io/43baq) and post the result here.

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/cc3e8aee8912f5ce3d367d003bb6dd46

**Comment by NeganSmith92** [comment]
Zafran Marvis
21181300
https://gist.github.com/NeganSmith92/45c5a3ce1441066d9c5712bc27ea8865

**Comment by charlesmana** [comment]
Charnadi Lesmana
21181068
https://gist.github.com/charlesmana/949e22bb85db8106b55854bee1f5625d

**Comment by yunoooo111** [comment]
Yurnero Nolla
21181296
https://gist.github.com/yunoooo111/8f33bf56fe5ebd7a95d78560f75f6995

**Comment by NerdyVandheka** [comment]
NERDY VANDHEKA
21181213
https://gist.github.com/NerdyVandheka/6588a531a14169510e81fcc202987fa6

**Comment by CriticalOlymp** [comment]
Chandra Martadinata
21181064
https://gist.github.com/CriticalOlymp/c4191b0823dc931ce49ac514fba19c4c

**Comment by ayodyaadhi01** [comment]
AYODYA ADHI
21181017
https://gist.github.com/ayodyaadhi01/815734bce97955ca9ffd4bf6cae4ffa5

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA P
21181284
https://gist.github.com/tegarhermans/b0d047edb01045d41ac1da5f6dabb89f

**Comment by afrozhie** [comment]
Firman Andrian
21181094

https://gist.github.com/afrozhie/656029e62efba4c7c9dc6664f3a222a8

**Comment by MazamGanendra** [comment]
Mazam Ganendra
21181192

https://gist.github.com/MazamGanendra/4e681a1101c9e3ac2e79552dca0b2a7a

**Comment by Antara000** [comment]
Makmur Perkasa
21181161
https://gist.github.com/Antara000/cbc322a54f498d2066c90adbb06b9d1e

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203
https://gist.github.com/Ptolemu5/3f0ba5415ad0ff304cb89c21e3f9ccf9

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203
https://gist.github.com/Ptolemu5/2c7822c7632fad396920c7d036e2d914

**Comment by AKS4R4** [comment]
Rasha Muhammad
 21181236
  https://gist.github.com/AKS4R4/8fa09cb0eb239eb176935ccb15e2769a

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085

https://gist.github.com/IZAN0R/3d87804ab1e426214a5d1b23cf57c7d6

**Comment by CyberianRonin** [comment]
Resna Febrianto
21181229

https://gist.github.com/CyberianRonin/bbd2a6bc369a21e2d954a156d7b41143

**Comment by bahrudinz** [comment]
Mudzafar Azzam
2118117

https://gist.github.com/bahrudinz/997b8d12228a7c46235642dfda2f36e0
