### ISSUE TITLE
Lecture 17-May-2024, Session 14 Presentation of ML Topics

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#14]
+ Read [the slide](https://osf.io/aykwd).
+ Read [a story](https://medium.com/p/fc02c9b273bb) for cloning Python virtual environment supporting TensorFlow.
+ Create a group with 3 members.
+ Explore topics that will be solved using machine learning.
+ Present the topics:
  - One topic for each member,
  - Give the reason behind the topics, which includes \
    a. source of datasets, \
    b. availability of code. \
    c. Support of infrastructures. e.g. computer specifications.
+ Write all in a gist and share the link.
+ Put ID of all members in the gist, omit their names.

**Comment by NerdyVandheka** [comment]
KELOMPOK 1
1. AYODYA ADHI (21181017)
2. DIEGO PRADIPTA (21181085)
3. NERDY VANDHEKA (21181213)

https://gist.github.com/NerdyVandheka/9c17b618704266df72e8156114fbf811

**Comment by yunoooo111** [comment]
1. YURNERO NOLLA
2. TEGUH ANDHIVA PUTRA
3.  YULIA VALONIA

https://gist.github.com/yunoooo111/0c7883e8f5f015d0fc078b9c5f0589e2

**Comment by NeganSmith92** [comment]
1. Zafran Marvis (21181300)
2. Chandra Martadinata (21181064)
3. Irham Prajawiguna (21181125)

https://gist.github.com/NeganSmith92/1bca6babe8d606038c83daa44ede1f22

**Comment by charlesmana** [comment]
1. CHARNADI LESMANA
2. MUDZAFAR AZZAM
3. FALIH MARTADINATA

https://gist.github.com/charlesmana/8c690c9051750a1ec2312d0f2a76c543

**Comment by afrozhie** [comment]
1. FIRMAN ANDRIAN
2. MULIA NARAPATI
3. ROBIN HUDSON

https://gist.github.com/afrozhie/82f473c89a9a232d4efc432039a293a1

**Comment by MazamGanendra** [comment]
1. Diman Alfon ( 21181074 )
2. Heksandro Molako ( 21181117 )
3. Mazam Ganendra ( 21181192 )

https://gist.github.com/MazamGanendra/8126a913dba0accf389c95d88583db47
