### ISSUE TITLE
Lecture 19-Feb-2024, Session 3 Review and Mastering Python List for Data Science

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#3]
+ Read how to share your Jupyter Notebook `ipynb` file on GitHub Gist \
  https://medium.com/p/950dccdc3f5d
+ Perform activities on slide \
  https://osf.io/rxu7v
+ Do the 10 exercises on a Jupyter notebook file, share it on your Gist, and write link to your gist here.
+ Do not forget to inform your ID as you post link to your gist.

**Comment by CriticalOlymp** [comment]
NIT : 21181064

https://gist.github.com/CriticalOlymp/d49904beae732b76240e1a38f6170f5d
https://medium.com/@cahyasatya14/notebook-for-gist-github-fb28f153bfbb
https://gist.github.com/CriticalOlymp/48e39f868038ef0c18e0c071b02faffa

**Comment by charlesmana** [comment]
Nama : Charnadi Lesmana
NIT : 21181068
https://gist.github.com/charlesmana/6899ba6510e62086ca1ee83b298a862c
https://medium.com/@citayogiprtm6/https-gist-github-com-charlesmana-6899ba6510e62086ca1ee83b298a862c-a0bf9885b93d
exercise:
https://gist.github.com/charlesmana/42504d2d3cbc00550e83b8ae94c38226

**Comment by tegarhermans** [comment]
21181284

test
https://gist.github.com/tegarhermans/609e1fd0aa0ad865a2581c47c2120075
https://medium.com/@saputrotegar.st/notebook-for-gist-ipynb-edca0e33d3fa

exercise
https://gist.github.com/tegarhermans/f2243d87959ba857afdbf1b2cf231814
https://medium.com/@saputrotegar.st/exercise-ipynb-40961c95445c

**Comment by narapatimulia** [comment]
21181195
https://gist.github.com/narapatimulia/10af279598282bdf3c11aa439f07262c
https://medium.com/@patinarapati/test-jupyter-notebook-with-gist-7a403b2ebef2
https://gist.github.com/narapatimulia/9d151dd3902e5805214bbe2dbe7bbc8d

**Comment by yunoooo111** [comment]
21181296
https://gist.github.com/yunoooo111/db01b554d1c030919bfec04ba40b3024

**Comment by afrozhie** [comment]
21181094
https://gist.github.com/afrozhie/9f4d298c6a417273ba398584aaa8e33c

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241

https://gist.github.com/birongzah/88165de6223a04d898729cc87d59f274
https://medium.com/@reinaldoulian/githublink-4e6644479619
https://gist.github.com/birongzah/2023eb089b3feac9f971efc260b064a9

**Comment by NeganSmith92** [comment]
NAMA : ZAFRAN MARVIS
NIT : 21181300
https://gist.github.com/NeganSmith92/f4177eca89875d7711efa1ebde762f74
https://medium.com/@zfadhlurramadhan2911/https-gist-github-com-negansmith92-f4177eca89875d7711efa1ebde762f74-b5b8e612f6a0
EXERCISE :
https://gist.github.com/NeganSmith92/1c486bdd8f4537c3acd0dae0ceaf618e

**Comment by yunisangadji** [comment]
NIT : 21181298
https://gist.github.com/yunisangadji/45be53be95330c2120cc4224665249be
https://medium.com/@yuniasangadji/share-jupyter-notebook-menggunakan-gist-dan-tambahkan-dalam-stor-f840b717194e

Exercise:
https://gist.github.com/yunisangadji/9f5508d01548f0bf0250f9cbcc702daa

**Comment by ayarayenima** [comment]
Nama : Ayara Yenima
NIT : 21181032
https://gist.github.com/ayarayenima/25f2d107b83c5694aacc75e1711cfe40

**Comment by bahrudinz** [comment]
NIT : 21181177

https://gist.github.com/bahrudinz/1da7af6b52dabd1a8b7bd3f68053bc48
https://medium.com/@bahrudinnafa01/https-gist-github-com-bahrudinz-1da7af6b52dabd1a8b7bd3f68053bc48-543bb46c9b17
https://gist.github.com/bahrudinz/13fd43ebb3e12fc27d408166b6aa9110

**Comment by MazamGanendra** [comment]
NIT : 21181192
https://gist.github.com/MazamGanendra/731af2d31e63bc02adfae321bb672c94

**Comment by CyberianRonin** [comment]
NIT : 21181229
https://gist.github.com/CyberianRonin/7aa626aec55180e3e5500e123186df93
https://medium.com/@febriantoresna/gist-8ec408be7890

**Comment by Antara000** [comment]
Nama : Makmur Perkasa
NIT : 21181161

- https://gist.github.com/Antara000/81cf4ac5b288625d859aa5fae2fe72b0
- https://medium.com/@shakty209/this-is-how-i-do-it-a137f6ec4e88
- https://gist.github.com/Antara000/b6c27a8858810ebad4cc4ae36c583892

**Comment by MazamGanendra** [comment]
NIT : 21181192

https://gist.github.com/MazamGanendra/c693f071efcbb9893bb96817790ed6c9
https://medium.com/@masjhurhusein/sharing-my-jupyter-notebook-in-me-0ac941b93343

Exercise : 
https://gist.github.com/MazamGanendra/0baeabdf39390f1016563a8abdde7af9

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

NIST :
https://medium.com/@murrobifath1/notebook-for-gist-ipnyb-bc2412e9d9af

Python List Exercise : 
https://medium.com/@murrobifath1/python-list-exercise-c88f139d7dc8

**Comment by NerdyVandheka** [comment]
Nama : Nerdy Vandheka 
NIT : 21181213

https://gist.github.com/NerdyVandheka/d04f825fbe34936b904ab0098346456c
https://medium.com/@crewsakan1312/project-issues-3-nerdy-1b43bfff0de3?postPublishedType=initial

Exercise :
https://gist.github.com/NerdyVandheka/571e9558d66e799fbefad20829e7237f
https://medium.com/@crewsakan1312/exercise-issues-3-06491ca24502

**Comment by IZAN0R** [comment]
Diego Pradipta
21181085

test
https://gist.github.com/IZAN0R/e5f4c9f5af3c8eb538427b2b74f4060a

Exercise
https://gist.github.com/IZAN0R/fef8518808b7cb5cbf05025a360d4886
https://medium.com/@yayawsutaryaw/share-a-jupyter-notebook-using-github-gist-8eaef118e273

**Comment by irhwam** [comment]
NIT: 21181125

Test: https://gist.github.com/irhwam/213bbddc3534027da9ba730508a72ccf
Exercise: https://gist.github.com/irhwam/e439044a9455d5cd36c7409189548dcd

Medium: https://medium.com/@prajawigoona/python-jupyter-exercise-2e4ba139c179

**Comment by ayodyaadhi01** [comment]
NAMA : AYODYA ADHI
NIT : 21181017

https://gist.github.com/ayodyaadhi01/457dec712e67558624c37bc2656bd1ac
https://medium.com/@yoday5852/gist-cb428ffa3d54

**Comment by robinhuud15** [comment]
NAMA : Robin Hudson
NIT : 21181234
https://gist.github.com/robinhuud15/6873f9c2d885dbc77bccd7b926a6f07e
https://medium.com/@raflymaulana1508/ro-6567f7a47007

**Comment by c4t4r** [comment]
NIT : 21181074
https://gist.github.com/c4t4r/601d7562d808d2671a6cfdb6152fb510

**Comment by AKS4R4** [comment]
NIT : 21181236
Nama : Rasha Muhammad
https://gist.github.com/AKS4R4/4f17875fdd1911ab9e8d69729c033868

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/ecd28cb240ae987c40c83abf19572c27
https://medium.com/@keweranto45/https-gist-github-com-fadhilahdhils-2715e5c0afea2a687b86b1e81cd558d0-959617760853
https://gist.github.com/fadhilahdhils/182af1bdbdb21d650af4e790e6a296b1
