### ISSUE TITLE
Lecture 19-Feb-2024, Session 4 Data Visualization in Python using Matplotlib

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#4]
+ Read following stories
  - [691856368592](https://medium.com/p/691856368592) (Point: 10)
  - [23de1e39d16e](https://medium.com/p/23de1e39d16e) (Point: 10)
  - [ca11427ac966](https://medium.com/p/ca11427ac966) (Point: 10)
  - [f78eea5da275](https://medium.com/p/f78eea5da275) (Point: 10)
+ Practice to create
  - Line plot  (Point: 20)
  - Scatter plot  (Point: 20)
  - Controur plot  (Point: 20)
 + Put all the result on a Jupyter Notebook file, share it as a gist, and put the link here, accompanied with your ID.

**Comment by yunoooo111** [comment]
Nama = Yurnero Nolla
NIT = 21181296
https://gist.github.com/yunoooo111/af3fdee1188385e508ad414e3938598f

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195
Link : https://gist.github.com/narapatimulia/10af279598282bdf3c11aa439f07262c

**Comment by yunisangadji** [comment]
NIT : 21181298
https://gist.github.com/yunisangadji/45be53be95330c2120cc4224665249be

**Comment by CyberianRonin** [comment]
Nama : Resna Febrianto
NIT : 21181229
https://gist.github.com/CyberianRonin/1aa34c428b804a3662276652a058c762

**Comment by Kodhil** [comment]
Nama:Falih Martadinata
NIT:21181092
https://gist.github.com/Kodhil/06c77105a3d399881421e7e9f1ec40a1

**Comment by c4t4r** [comment]
NIT:21181074
https://gist.github.com/c4t4r/1ac6406f4bb27b181a3aec1b479eada9

**Comment by CyberianRonin** [comment]
Nama : Resna Febrianto
NIT : 21181229
https://gist.github.com/CyberianRonin/1aa34c428b804a3662276652a058c762

**Comment by irhwam** [comment]
NIT: 21181125

https://gist.github.com/irhwam/6fe0b3dd24865b5b8f1f63d1442f48e0

**Comment by robinhuud15** [comment]
Nama : Robin Hudson
NIT : 21181234
https://gist.github.com/robinhuud15/6eb2cde62da0768f1e65657f60a0ae71

**Comment by MazamGanendra** [comment]
NIT : 21181192
https://gist.github.com/MazamGanendra/731af2d31e63bc02adfae321bb672c94

**Comment by CriticalOlymp** [comment]
21181064

https://gist.github.com/CriticalOlymp/d49904beae732b76240e1a38f6170f5d

**Comment by tegarhermans** [comment]
21181284

https://gist.github.com/tegarhermans/22df774d2ab6847205d7ee9779bda043
https://gist.github.com/tegarhermans/551e33a1e2a1475e4976c421467bd7c0
https://gist.github.com/tegarhermans/1a73c7b4da715d7f88242ac1cd8db0ad
https://gist.github.com/tegarhermans/d4682d7680f8634f7b80de89cf424322

https://medium.com/@saputrotegar.st/exercise2-1-a7aa07f84e38
https://medium.com/@saputrotegar.st/exercise2-2-54fa15d31364
https://medium.com/@saputrotegar.st/exercise2-3-8ea1fe6df721
https://medium.com/@saputrotegar.st/exercise2-4-0e82360fe8dd

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241

https://gist.github.com/birongzah/0356b2f9f75753cbcd98b8679c8eb236

**Comment by NeganSmith92** [comment]
NAMA : ZAFRAN MARVIS
NIT : 21181300
https://gist.github.com/NeganSmith92/87dcdd33fc1f0b7d684bd9405e566ac9

**Comment by afrozhie** [comment]
21181094
https://gist.github.com/afrozhie/9df3b6c9480aad2e35f98bc0484a6ece

**Comment by NerdyVandheka** [comment]
Nama : Nerdy Vandheka
NIT : 21181213
https://gist.github.com/NerdyVandheka/aaea9cefb3baa3eb6d4da78f9f65977c

**Comment by bahrudinz** [comment]
NIT : 21181177
https://gist.github.com/bahrudinz/c8502f95855b67f32fd808868ad1efeb

**Comment by charlesmana** [comment]
NIT : 21181068
1. https://gist.github.com/charlesmana/7e63f544f1599fde5cb2b994817ad86a
2. https://gist.github.com/charlesmana/f23e9d0fe15eba4f471985600ad7122b
3. https://gist.github.com/charlesmana/f62df77e82c3e1da39a5f9868eb9d37c
4. https://gist.github.com/charlesmana/a223d3f703f362fb75d8be34cc90ffc5

https://gist.github.com/charlesmana/58e1f8b64e5764ac74d9f20316656a64

**Comment by ayodyaadhi01** [comment]
NAMA : AYODYA ADHI
NIT : 21181017

https://gist.github.com/ayodyaadhi01/d3849dedd1a1682cf7961b964c64506e

**Comment by Antara000** [comment]
NAMA : MAKMUR PERKASA
NIT : 21181161

https://gist.github.com/Antara000/34ca046e25ec3f40591bb431a51e7117

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

https://gist.github.com/Ptolemu5/b5bacc6bd682dfce0f99aba56cf4f0a6

**Comment by IZAN0R** [comment]
Diego Pradipta
21181085

https://gist.github.com/IZAN0R/f6a1e1589c08bccba4d1ed3a57afee8f

**Comment by ayarayenima** [comment]
NIT : 21181032
https://gist.github.com/ayarayenima/cff612898cc16c82898dfc371a146f93

**Comment by AKS4R4** [comment]
NIT : 21181236
Nama : Rasha Muhammad
https://gist.github.com/AKS4R4/813ea4c7f8baed28e7b8cde583f0bffd

**Comment by heksamolako25** [comment]
21181117
Heksandro M

https://gist.github.com/heksamolako25/2050b6b33d9d9e73bcd90b9e1b39d45d
