### ISSUE TITLE
Lecture 23-Feb-2024, Session 5 Python and pandas DataFrame

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#5]
+ Read the slides for today lectures ([slide-1](https://osf.io/kgw5f), [slide-2](https://osf.io/6t48k))
+ Do the exercises.
+ Try to read following files and plot the data
  - [lissajous_circle.xlsx](https://github.com/dudung/mk-data-sains/files/14380930/lissajous_circle.xlsx)
  - [lissajous_butterfly.xlsx](https://github.com/dudung/mk-data-sains/files/14380947/lissajous_butterfly.xlsx)
  - [distribution.xlsx](https://github.com/dudung/mk-data-sains/files/14381121/distribution.xlsx)
  - [fruit_pie_chart.xlsx](https://github.com/dudung/mk-data-sains/files/14381174/fruit_pie_chart.xlsx)
  - [contour.xlsx](https://github.com/dudung/mk-data-sains/files/14381270/contour.xlsx) &rightarrow; read [this article](https://alexmiller.phd/posts/contour-plots-in-python-matplotlib-x-y-z/)
+ Make notebook containing answers to the exercises.
+ Post the notebook as a gist on your GitHub Gist account (as in [previous slide](https://osf.io/pxcra))
+ Write link to the gist here and also your ID (do not forget this information).

**Comment by yunoooo111** [comment]
Nama: Yurnero Nolla
NIT : 21181296

https://gist.github.com/yunoooo111/a291c26ddfaecfcbeb97ad83835483b6

**Comment by NerdyVandheka** [comment]
NAMA : NERDY VANDHEKA
NIT : 21181213
ABSEN : 16
https://gist.github.com/NerdyVandheka/6775168ead8befc26e7b0c4e70e8dffe
https://gist.github.com/NerdyVandheka/fb08576c0214fa2ca1e67b3aad703658

**Comment by birongzah** [comment]
NAMA : REINALDO ULIAN
NIT : 21181241

https://gist.github.com/birongzah/8e008e5b914982abf12de7b1287404e6

**Comment by tegarhermans** [comment]
21181284
TEGUH ANDHIVA PUTRA

1. today lectures
https://gist.github.com/tegarhermans/b2e053fdb84c853e9675bc925e57a8a1
2. plotting data task
https://gist.github.com/tegarhermans/51b58e706976e2c3b5d7369ee9f16aca

**Comment by CriticalOlymp** [comment]
21181064
chandra martadinata

https://gist.github.com/CriticalOlymp/99774c6ac0a68d4f4fd8262ab1e166dc

**Comment by NeganSmith92** [comment]
- NIT : 21181300

- NAMA : ZAFRAN MARVIS

- LINK GIST : https://gist.github.com/NeganSmith92/ff9b4f14162a9825083496bdd9a190e6

**Comment by afrozhie** [comment]
21181094

https://gist.github.com/afrozhie/51b2074592afb48dca74d43f24f2a56d

**Comment by MazamGanendra** [comment]
21181192

https://gist.github.com/MazamGanendra/a77532c49b863901867f0330002a67d3

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195

https://gist.github.com/narapatimulia/32169c1ff3099c87448cad80e400c56f

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

https://gist.github.com/Ptolemu5/30f537f5c2ff24ec2252972f8481841f

**Comment by yunisangadji** [comment]
21181298
https://gist.github.com/yunisangadji/aa11dfc8bbda7db56ccfc62107be4ddc

**Comment by charlesmana** [comment]
NIT : 21181068
https://gist.github.com/charlesmana/29e3f3a280f8931ff595f2a80e1187ff

**Comment by CyberianRonin** [comment]
NIT : 21181229
https://gist.github.com/CyberianRonin/ed7dd46f352f6337a7123c4c654c9ac7
https://gist.github.com/CyberianRonin/3859d3d61bf10e1e0fa5919703ecc440

**Comment by ayarayenima** [comment]
NIT : 21181032
https://gist.github.com/ayarayenima/40d71c35f91fc2d2f07b9d73605f7002

**Comment by AKS4R4** [comment]
NIT : 21181236
Nama : Rasha Muhammad
https://gist.github.com/AKS4R4/ed54c1464a31164b1882ec85a94ea47c

**Comment by heksamolako25** [comment]
NIT : 21181117
NAMA : HEKSANDRO MOLAKO
[assignment5_Heksandro.zip](https://github.com/dudung/mk-data-sains/files/14398634/assignment5_Heksandro.zip)

**Comment by ayodyaadhi01** [comment]
NAMA : AYODYA ADHI
NIT : 21181017
https://gist.github.com/ayodyaadhi01/cdf670ba576d4d677ec22c0213e09f41
https://gist.github.com/ayodyaadhi01/8147c462d6cf3b2b3e85dfd393bf01d4

**Comment by Antara000** [comment]
NAMA : MAKMKUR PERKASA
NIT : 21181161

https://gist.github.com/Antara000/6c5f73c40634ed475c0dbd6d387a90f0

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085
https://gist.github.com/IZAN0R/99865178c73be6ade7b705034fc016a2

**Comment by c4t4r** [comment]
NIT 21181074
https://gist.github.com/c4t4r/7492125ac0ec06761707791a9a0e3d21

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085
https://gist.github.com/IZAN0R/7715c45985d16f5cb27ed3689b8e5239

**Comment by bahrudinz** [comment]
NIT : 21181177
Nama : Mudzafar Azzam

Link : https://gist.github.com/bahrudinz/295daf084f3f2cdd0fbba27794cf124a

**Comment by robinhuud15** [comment]
https://gist.github.com/robinhuud15/052ac3510e272ea2950e73470ceaecb2

**Comment by robinhuud15** [comment]
NIT : 21181234
NAMA : ROBIN HUDSON
https://gist.github.com/robinhuud15/3a62cb2de8d8c3ee29526251eb55b2b6

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/e8c95b977412ef3ded7e2c9551cc5aa1

**Comment by irhwam** [comment]
NIT: 21181125
Irham Prajawiguna

https://gist.github.com/irhwam/c21b0332dddad3140332a26e052120b8
