### ISSUE TITLE
Lecture 26-Feb-2024, Session 6 Descriptive Statistics with Python

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#6]
+ Follow today session ([slide](https://osf.io/zqkv9))
+ Do the examples and exercises in a notebook.
+ Upload the notebook as a gist.
+ Write link to the gist here.

**Comment by c4t4r** [comment]
NIT 21181074
https://gist.github.com/c4t4r/9abbb164703017063385cd5a008612dd

**Comment by NerdyVandheka** [comment]
NERDY VANDHEKA
21181213
https://gist.github.com/NerdyVandheka/6d85c801021090759f883a686b28210c

**Comment by CriticalOlymp** [comment]
21181064

https://gist.github.com/CriticalOlymp/0ea5a9bbe12d8e1acef3484de167d53f
https://gist.github.com/CriticalOlymp/a99ac6ba92d79e5e27ab5bcff62211b8

**Comment by NeganSmith92** [comment]
- NIT : 21181300

- NAMA : ZAFRAN MARVIS

- LINK GITHUB : https://gist.github.com/NeganSmith92/69a7709b0b63d4141c74e154d785d5b9

**Comment by tegarhermans** [comment]
21181284
TEGUH ANDHIVA PUTRA

https://gist.github.com/tegarhermans/6d472e4cfd0e893141f8895007fe78eb

**Comment by afrozhie** [comment]
21181094

https://gist.github.com/afrozhie/73ae136a462642bbdbf518420fe4b18a

**Comment by ayodyaadhi01** [comment]
NAMA : AYODYA ADHI
NIT : 21181017

https://gist.github.com/ayodyaadhi01/7065046d255be2ad88fed1e6baac19c5

**Comment by MazamGanendra** [comment]
NIT : 21181192
https://gist.github.com/MazamGanendra/461db14cad407321d354a01ae7719458

**Comment by Antara000** [comment]
NAMA : MAKMUR PERKASA
NIT : 21181161
https://gist.github.com/Antara000/3161e13086e14ae60987128c095875f8

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

https://gist.github.com/Ptolemu5/64fd186f180749d797b078e10dc3a753

**Comment by yunoooo111** [comment]
Nama: Yurnero Nolla
NIT: 21181296

https://gist.github.com/yunoooo111/2f6a898b2fd7006d4e19f8194f226627

**Comment by narapatimulia** [comment]
Name : Mulia Narapati
 NIT : 21181195

https://gist.github.com/narapatimulia/3c00c8ac6c2bee316bada9541fac2119

**Comment by CyberianRonin** [comment]
Name : Resna Febrianto
NIT : 21181229

https://gist.github.com/CyberianRonin/a7a03229525370e5ac4f2110d1ad561a

**Comment by charlesmana** [comment]
NIT : 21181068
https://gist.github.com/charlesmana/1f06ed0b855fa47bd3185c2c27658254

**Comment by IZAN0R** [comment]
Diego Pradipta
21181085

https://gist.github.com/IZAN0R/a92088e5c1974d2fb4c4b5aa97c0b7b7

**Comment by yunisangadji** [comment]
21181298
YULIA VALONIA

https://gist.github.com/yunisangadji/391f54ef9593f2ea99e763fb0d3412fc

**Comment by AKS4R4** [comment]
Rasha Muhammad
21181236
https://gist.github.com/AKS4R4/4b75ae326b7f2977823c2696af1436c7

**Comment by bahrudinz** [comment]
NIT : 21181177
Nama : Mudzafar Azzam

Link : https://gist.github.com/bahrudinz/a9c9d18a5cccf027956e1a455708dd1b

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241

https://gist.github.com/birongzah/0759833ae1602701d27afec3b1a1cf64

**Comment by robinhuud15** [comment]
NAMA : ROBIN HUDSON
NIT : 21181234

https://gist.github.com/robinhuud15/9c50280cc985accc7c828280d0195dc4

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/4c39cbb822023f398572660afa1d8165

**Comment by irhwam** [comment]
NIT: 21181125
NAMA: IRHAM PRAJAWIGUNA

https://gist.github.com/irhwam/9b30cd4c1ba259933aecf46d10d95f8c

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/aa2209392d1201e4bb3c0f6137c584c8

**Comment by heksamolako25** [comment]
NIT : 21181117
HEKSANDRO MOLAKO

https://gist.github.com/heksamolako25/0c0d608565c339fdc165e096e651de58
