### ISSUE TITLE
Lecture 26-Feb-2024, Session 7 Materials review

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#7]
+ Review all previous materials in a notebook.
  - [slide-1](https://osf.io/42mhj)
  - [slide-2](https://osf.io/zp7tq)
  - [slide-3a](https://osf.io/pxcra), [slide-3b](https://osf.io/rxu7v)
  - [slide-4a](https://osf.io/zp2y7), [slide-4b](https://osf.io/saf8z)
  - [slide-5a](https://osf.io/kgw5f), [slide-5b](https://osf.io/6t48k)
  - [slide-6](https://osf.io/zqkv9)
+ Put only what do you think important.
+ This will be used as cheat sheet in the mid term.
+ Upload the notebook as a gist.
+ Write link to the gist here.

**Comment by CriticalOlymp** [comment]
21181064

https://gist.github.com/CriticalOlymp/1aba5e0a5b130adb73df10c78781c714

**Comment by NerdyVandheka** [comment]
NAMA : NERDY VANDHEKA
NIT : 21181213
ABSEN : 16

https://gist.github.com/NerdyVandheka/2fc418364b2a90c5c505909965757dba

**Comment by NeganSmith92** [comment]
- NAMA : ZAFRAN MARVIS
- NIT : 21181300
- LINK GIST : https://gist.github.com/NeganSmith92/0220fd636478490361d3b83d2b584d2e

**Comment by AKS4R4** [comment]
Rasha Muhammad
21181236
https://gist.github.com/AKS4R4/4b75ae326b7f2977823c2696af1436c7

**Comment by CyberianRonin** [comment]
Nama : RESNA FEBRIANTO
NIT : 21181229

https://gist.github.com/CyberianRonin/739a868f6bff55979d1e049779b8817f

**Comment by ayodyaadhi01** [comment]
NAMA : AYODYA ADHI
NIT : 21181017

https://gist.github.com/ayodyaadhi01/d762e828592219da24863b277dfbd650

**Comment by bahrudinz** [comment]
NIT : 21181177
Nama : Mudzafar Azzam

Link : https://gist.github.com/bahrudinz/43c40bce2f289a47d12b21816c62ca8a

**Comment by MazamGanendra** [comment]
21181192

https://gist.github.com/MazamGanendra/9dca57d3e402145fdc4bae7eb50fbef7

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241

https://gist.github.com/birongzah/6c53d85b2f33720aac888b7e0b51ae58

**Comment by robinhuud15** [comment]
NAMA : ROBIN HUDSON
NIT : 21181234

https://gist.github.com/robinhuud15/723d332f29dbae04f6dd388f11fe7730

**Comment by yunoooo111** [comment]
Yurnero Nolla
21181296

https://gist.github.com/yunoooo111/2d1e89952e68b16b3593d4b2bc2ed7cb

**Comment by Ptolemu5** [comment]
Murrobi F
21181203

https://gist.github.com/Ptolemu5/afbf955d0e41630e5e39cc8181dbf3b7

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA PUTRA 
21181284

https://gist.github.com/tegarhermans/eb28b3fd9b83950eee5f7229fe1196e3

**Comment by yunisangadji** [comment]
YULIA VALONIA 
21181298

https://gist.github.com/yunisangadji/a9657142fd5038edaaffad9def75e3ff

**Comment by afrozhie** [comment]
FIRMAN ANDRIAN
21181094

https://gist.github.com/afrozhie/4457ff2ae4ee4dffa29823080edb6c0a

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/7e37aa623c7187b7842530ea2a8d609d

**Comment by IZAN0R** [comment]
Diego Pradipta
21181085
https://gist.github.com/IZAN0R/65b6203642428b0d1099cf3ee4fd7bc7

**Comment by charlesmana** [comment]
CHARNADI LESMANA
21181068
https://gist.github.com/charlesmana/2ff1351ed7da592ecb11a4fcca798387

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/4c39cbb822023f398572660afa1d8165

**Comment by irhwam** [comment]
NIT: 21181125
Irham Prajawiguna

https://gist.github.com/irhwam/d6638279dcdb7cbefad779e6f84588af

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/b908bafeb793086fdd390f422fb67f6a

**Comment by AKS4R4** [comment]
RASHA MUHAMMAD
21181236
https://gist.github.com/AKS4R4/bcb93337c5831ec0ba01b74b70d9e318
Support by : Zafran Marvis

**Comment by heksamolako25** [comment]
Heksandro Molako
21181117

https://gist.github.com/heksamolako25/3cc73c238375600375d79d63310c1231
