### ISSUE TITLE
Lecture 04-Apr-2024, Session 8 Data and data source

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#8]
+ Make a resume of this materials in a notebook.
+ Upload it as a gist.
+ Share link to the gist here.

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
link : https://gist.github.com/NeganSmith92/9e8dd147ab74a5f6afef5db11f37c862

**Comment by CyberianRonin** [comment]
RESNA FEBRIANTO
21181229
Link : https://gist.github.com/CyberianRonin/7f867a3fc5d7d0da0f06354b00dbc685

**Comment by NerdyVandheka** [comment]
NERDY VANDHEKA
21181213
TAUTAN : https://gist.github.com/NerdyVandheka/95128f41fcdc10388eee067f77f2619b

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241
Link : https://gist.github.com/birongzah/917a93233cfecde2214d41b6632ef251

**Comment by ayodyaadhi01** [comment]
AYODYA ADHI
21181017
LINK : https://gist.github.com/ayodyaadhi01/2f3d74e24b4b54152bf196a23cb1c128

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA PUTRA
21181284
https://gist.github.com/tegarhermans/b51c947195c715316758cb6871898766

**Comment by yunoooo111** [comment]
Yurnero Nolla
21181296

LINK : https://gist.github.com/yunoooo111/07cca70c727baeb7d8c697577f79d0cb

**Comment by MazamGanendra** [comment]
Mazam Ganendra
21181192

https://gist.github.com/MazamGanendra/bc626d352921e740038426bfb2d411db

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195

https://gist.github.com/narapatimulia/cbfd9720a918753900add29987c9ab23

**Comment by afrozhie** [comment]
FIRMAN ANDRIAN
21181094

https://gist.github.com/afrozhie/975c83a4c4157241775128cf3739af41

**Comment by charlesmana** [comment]
CHARNADI LESMANA
21181068
https://gist.github.com/charlesmana/7d91c75a48f76779f5cb1ac2777efdf2

**Comment by Antara000** [comment]
MAKMUR PERKASA
21181161
https://gist.github.com/Antara000/58bb8da93f18fb4495e817ae1b523b8c

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203
https://gist.github.com/Ptolemu5/a73f099c56c690db620075a0316ca214

**Comment by yunisangadji** [comment]
Yulia Valonia
21181298
https://gist.github.com/yunisangadji/7c42be7566154b7005d47f27ab3b01f2

**Comment by CriticalOlymp** [comment]
CHANDRA MARTADINATA
21181064
https://gist.github.com/CriticalOlymp/656893b95f68cc80dea112bc69243d37

**Comment by bahrudinz** [comment]
MUDZAFAR AZZAM
21181177

https://gist.github.com/bahrudinz/86f2e69c97901fde48477782f096fe29

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085

https://gist.github.com/IZAN0R/7622d84345ed4a61762cc62bdda5e233

**Comment by robinhuud15** [comment]
ROBIN HUDSON
21181234

https://gist.github.com/robinhuud15/dca5d77c13d4cbe0f4bd003736b3f164

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/4d22a58428df49779becf59efdd18340

**Comment by irhwam** [comment]
NIT: 21181125
Irham Prajawiguna
https://gist.github.com/irhwam/94db297bdc45cfbc330170162973bb29

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/b04ec11cf27fa807d15a1f448cb73a85

**Comment by AKS4R4** [comment]
RASHA MUHAMMAD
21181236
https://gist.github.com/AKS4R4/22589925d6eb970fdf9788a1bbc10b00
Support by : Zafran Marvis

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/a54a4beee72cf5ae53484dcd824254a6

**Comment by heksamolako25** [comment]
21181117

https://gist.github.com/heksamolako25/1af8815dd24947737637232af4070768
