### ISSUE TITLE
Lecture 04-Apr-2024, Session 9 Monte Carlo and Fourier transform

### ISSUE THREAD

**Issue by dudung** [dudung/mk-data-sains#9]
- Make a resume of this materials in a notebook.
- Upload it as a gist.
- Share link to the gist here.

**Comment by CyberianRonin** [comment]
Resna Febrianto
21181229
Link : https://gist.github.com/CyberianRonin/8e2535d43124dfe89adab26fedef62f1

**Comment by NerdyVandheka** [comment]
NERDY VANDHEKA
21181213
TAUTAN : https://gist.github.com/NerdyVandheka/ea6e948801db6483bb11d26d318812be

**Comment by afrozhie** [comment]
FIRMAN ANDRIAN
21181094

https://gist.github.com/afrozhie/b7a2c96556b4e50fb8f12d0daae1e358

**Comment by ayodyaadhi01** [comment]
AYODYA ADHI
21181017
LINK : https://gist.github.com/ayodyaadhi01/2c2bf6c27b16d8b1c41db3c351b09fd7

**Comment by tegarhermans** [comment]
TEGUH ANDHIVA PUTRA
21181284
https://gist.github.com/tegarhermans/3df368e30914978e0bdc6dec2d4248e5

**Comment by narapatimulia** [comment]
Mulia Narapati
21181195

https://gist.github.com/narapatimulia/92ce25cd9179d7432c98055fe2a57693

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
Link : https://gist.github.com/NeganSmith92/889fafc48b2eac1d8673ae1d1f3cebbc

**Comment by Ptolemu5** [comment]
Murrobi Fatahillah
21181203

https://gist.github.com/Ptolemu5/8df98698b9978b26698ac0e241f43da7

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
https://gist.github.com/NeganSmith92/4086ac178ec8709c57ad1ad5b1d5e071

**Comment by NeganSmith92** [comment]
ZAFRAN MARVIS
21181300
LINK : https://gist.github.com/NeganSmith92/aab8ad91efec160778ce923e5b2a2c73

**Comment by MazamGanendra** [comment]
Mazam Ganendra
21181192
https://gist.github.com/MazamGanendra/106b0f7c8e23eb4885cd9f3be15f8d7f

**Comment by Antara000** [comment]
MAKMUR PERKASA
21181161
https://gist.github.com/Antara000/28258786055bdf1e0393a75ecf6f590b

**Comment by CriticalOlymp** [comment]
CHANDRA MARTADINATA
21181064
https://gist.github.com/CriticalOlymp/656893b95f68cc80dea112bc69243d37

**Comment by CriticalOlymp** [comment]
CHANDRA MARTADINATA
21181064
https://gist.github.com/CriticalOlymp/9b104947d864086ea8f870289e146388

**Comment by bahrudinz** [comment]
MUDZAFAR AZZAM
21181177
https://gist.github.com/bahrudinz/7fa92cab8517d448f82a3f54f52382ea

**Comment by birongzah** [comment]
Reinaldo Ulian
21181241
https://gist.github.com/birongzah/93621a84f24cae762e373543a7bd5739

**Comment by IZAN0R** [comment]
DIEGO PRADIPTA
21181085
https://gist.github.com/IZAN0R/bba72084995c59db8f93ef60aac32c63

**Comment by yunisangadji** [comment]
YULIA VALONI
21181298
https://gist.github.com/yunisangadji/494ba9f1a62755ade7f216cd5d08e0cd

**Comment by robinhuud15** [comment]
ROBIN HUDSON 
21181234
https://gist.github.com/robinhuud15/c601f3cba7f29af458ef0276eaeddd72

**Comment by charlesmana** [comment]
CHARNADI LESMANA
21181068
https://gist.github.com/charlesmana/c5951aba2b45f9c29e47096f6478ae73

**Comment by fadhilahdhils** [comment]
NIT : 21181092
NAMA : FALIH MARTADINATA
https://gist.github.com/fadhilahdhils/dabc6836f59e98b2860c82b108fdc5a2

**Comment by yunoooo111** [comment]
Nama : Yurnero Nolla
NIT : 21181296

https://gist.github.com/yunoooo111/3cd2d6b6b71f4af47eaea654c4961aa5

**Comment by ayarayenima** [comment]
NIT : 21181032
LINK : https://gist.github.com/ayarayenima/e3fc67bc843b6bd8fd0b29c93e0626ea

**Comment by irhwam** [comment]
NIT: 21181125

https://gist.github.com/irhwam/5bbd0e4d334c8f74bca0415e51ba030e

**Comment by AKS4R4** [comment]
RASHA MUHAMMAD
21181236
https://gist.github.com/AKS4R4/b04e392b75abdc90fd2233989a307726
Support by : Zafran Marvis

**Comment by c4t4r** [comment]
Diman Alfon
21181074
https://gist.github.com/c4t4r/f79a0adaeddb6e9f3b88cd78905aa982

**Comment by heksamolako25** [comment]
Heksandro Molako
21181117

https://gist.github.com/heksamolako25/7dea706a825f8fbc718cb744a582addf
